{{- if and .Values.serviceAccount.create .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "satisfactory.roleBindingName" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "satisfactory.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "satisfactory.serviceAccountName" . | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "satisfactory.roleName" . | quote }}
{{- end }}
