{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "satisfactory.roleName" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "satisfactory.labels" . | nindent 4 }}
rules: [ ]
{{- end }}
