apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "satisfactory.fullname" . }}
  labels: {{- include "satisfactory.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
data:
  Engine.ini: |-
    [/Script/EngineSettings.GameMapsSettings]
    GameDefaultMap=/Game/FactoryGame/Map/GameLevel01/Persistent_Level
    LocalMapOptions=?sessionName=SatisfactoryServer?Visibility=SV_FriendsOnly?loadgame=savefile?listen?bUseIpSockets?name=Host

    [/Script/Engine.Player]
    ConfiguredInternetSpeed=104857600
    ConfiguredLanSpeed=104857600

    [/Script/OnlineSubsystemUtils.IpNetDriver]
    NetServerMaxTickRate=120
    MaxNetTickRate=400
    MaxInternetClientRate=104857600
    MaxClientRate=104857600
    LanServerMaxTickRate=120
    InitialConnectTimeout=300.0
    ConnectionTimeout=300.0

    [/Script/SocketSubsystemEpic.EpicNetDriver]
    MaxClientRate=104857600
    MaxInternetClientRate=104857600
  Game.ini: |-
    [/Script/Engine.GameNetworkManager]
    TotalNetBandwidth=104857600
    MaxDynamicBandwidth=104857600
    MinDynamicBandwidth=10485760

    [/Script/Engine.GameSession]
    MaxPlayers={{ .Values.satisfactory.maxPlayers }}
  Scalability.ini: |-
    [NetworkQuality@3]
    TotalNetBandwidth=104857600
    MaxDynamicBandwidth=104857600
    MinDynamicBandwidth=10485760
