apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "satisfactory.fullname" . }}
  labels: {{- include "satisfactory.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
data:
  Engine.ini: |-
    [/Script/EngineSettings.GameMapsSettings]
    GameDefaultMap=/Game/FactoryGame/Map/GameLevel01/Persistent_Level
    LocalMapOptions=?sessionName=SatisfactoryServer?Visibility=SV_FriendsOnly?loadgame=savefile?listen?bUseIpSockets?name=Host

    [/Script/Engine.Player]
    ConfiguredInternetSpeed=104857600
    ConfiguredLanSpeed=104857600

    [/Script/OnlineSubsystemUtils.IpNetDriver]
    NetServerMaxTickRate=120
    MaxNetTickRate=400
    MaxInternetClientRate=104857600
    MaxClientRate=104857600
    LanServerMaxTickRate=120
    InitialConnectTimeout=300.0
    ConnectionTimeout=300.0

    [/Script/SocketSubsystemEpic.EpicNetDriver]
    MaxClientRate=104857600
    MaxInternetClientRate=104857600

    [/Script/FactoryGame.FGSaveSession]
    mNumRotatingAutosaves=3

    [CrashReportClient]
    bImplicitSend={{ if .Values.satisfactory.reportCrashes }}True{{else}}False{{end}}
  Game.ini: |-
    [/Script/Engine.GameNetworkManager]
    TotalNetBandwidth=104857600
    MaxDynamicBandwidth=104857600
    MinDynamicBandwidth=10485760

    [/Script/Engine.GameSession]
    MaxPlayers={{ .Values.satisfactory.maxPlayers }}

  Scalability.ini: |-
    [NetworkQuality@3]
    TotalNetBandwidth=104857600
    MaxDynamicBandwidth=104857600
    MinDynamicBandwidth=10485760

  GameUserSettings.ini: |-
    [/Script/FactoryGame.FGGameUserSettings]
    mFloatValues=(("FG.AutosaveInterval", 300))
    mIntValues=(("FG.DisableSeasonalEvents", 0))
    mAudioVolumes=(Name="Master_Bus_Volume",Value=1.000000)
    mAudioVolumes=(Name="Ambient_Bus_Volume",Value=1.000000)
    mAudioVolumes=(Name="Factory_Bus_Volume",Value=1.000000)
    mAudioVolumes=(Name="Music_Bus_Volume",Value=0.500000)
    mAudioVolumes=(Name="SFX_Bus_Volume",Value=1.000000)
    mAudioVolumes=(Name="VO_Bus_Volume",Value=1.000000)
    mNetworkQuality=0
    mIsArachnophobiaMode=False
    mInvertY=False
    mAutoSortInventory=False
    mPrimaryLanguage=
    CurrentFGGameUserSettingsVersion=0
    bUseVSync=False
    bUseDynamicResolution=False
    ResolutionSizeX=1280
    ResolutionSizeY=720
    LastUserConfirmedResolutionSizeX=1280
    LastUserConfirmedResolutionSizeY=720
    WindowPosX=-1
    WindowPosY=-1
    FullscreenMode=1
    LastConfirmedFullscreenMode=1
    PreferredFullscreenMode=1
    Version=5
    AudioQualityLevel=0
    LastConfirmedAudioQualityLevel=0
    FrameRateLimit=0.000000
    DesiredScreenWidth=1280
    DesiredScreenHeight=720
    LastUserConfirmedDesiredScreenWidth=1280
    LastUserConfirmedDesiredScreenHeight=720
    LastRecommendedScreenWidth=-1.000000
    LastRecommendedScreenHeight=-1.000000
    LastCPUBenchmarkResult=-1.000000
    LastGPUBenchmarkResult=-1.000000
    LastGPUBenchmarkMultiplier=1.000000
    bUseHDRDisplayOutput=False
    HDRDisplayOutputNits=1000

    [ScalabilityGroups]
    sg.ResolutionQuality=100.000000
    sg.ViewDistanceQuality=3
    sg.AntiAliasingQuality=3
    sg.ShadowQuality=3
    sg.PostProcessQuality=3
    sg.TextureQuality=3
    sg.EffectsQuality=3
    sg.FoliageQuality=3
    sg.ShadingQuality=3

    [/Script/Engine.GameUserSettings]
    bUseDesiredScreenHeight=False

  ServerSettings.ini: |-
    [/Script/FactoryGame.FGServerSubsystem]
    mAutoPause=True
    mAutoSaveOnDisconnect=True
