on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run kics Scan
        uses: checkmarx/kics-action@v1.3
        with:
          fail_on: high
          path: 'charts'
          output_path: 'results.json'
